spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/truth_db
    username: postgres
    password: Ed0verlo.narva
    driver-class-name: org.postgresql.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        
server:
  port: 8080
  
logging:
  level:
    com.insightapp: DEBUG